---

- hosts: myhosts
  name: PowerEdge iDRAC Configuration
  gather_facts: False

  # Here we define global variables, but if some servers have different
  # credentials, then place these variables in /etc/ansible/hosts to override
  # for each host
  vars:
     rootdir: /root
     idracuser: root
     idracpswd: calvin

  # Options available:
  #   Reset		Reset all settings

  tasks:

  # CAUTION: All settings will be set to defaults, you could wind up losing
  # remote network access. Commenting out by default.
  - name: Reset configuration settings
    local_action: >
       idrac_config choice=Reset idracip={{ idracip }}
       idracuser={{ idracuser }} idracpswd={{ idracpswd }}

  # More options coming soon
  # SetupAlerts
  # SnmpSettings
  # EmailSettings
  # LicenseSettings 
  # VirtualConsole 
  # SessionManagement 
